### ISSUE TITLE
Can I convert your deepmimic mujoco xml to the format that can be loaded into unity3D?

### ISSUE THREAD

**Issue by hellozjj** [mingfeisun/DeepMimic_mujoco#4]
Is there any way that I can convert your deepmimic mujoco xml to the format that can be loaded into unity3D? How should I do that?

**Comment by mingfeisun** [comment]
Hi, thanks for your interest in the deepmimic mujoco xml. 
I have no idea of how to do that. I guess there is no way to automate this. It should be possible to create one manually.

**Comment by hellozjj** [comment]
> Hi, thanks for your interest in the deepmimic mujoco xml.
> I have no idea of how to do that. I guess there is no way to automate this. It should be possible to create one manually.

Thanks. I also notice you have commented some thing in deepmimic mujoco xml, but they are defined in deepmimic humanoid, like neck and shoulder. So why are they commented?

**Comment by hellozjj** [comment]
> Hi, thanks for your interest in the deepmimic mujoco xml.
> I have no idea of how to do that. I guess there is no way to automate this. It should be possible to create one manually.

The humanoid mujoco xml file has some error for deepmimic humanoid. Would you release the right vision later?

**Comment by mingfeisun** [comment]
Hi,
The correct version is at here `https://github.com/mingfeisun/DeepMimic_mujoco/blob/master/src/mujoco/humanoid_deepmimic/envs/asset/dp_env_v3.xml`

Other files are for debuging use. They are basically same as `dp_env_v3.xml`.  You can find the env settings from `config.py`

**Comment by mingfeisun** [comment]
> > Hi, thanks for your interest in the deepmimic mujoco xml.
> > I have no idea of how to do that. I guess there is no way to automate this. It should be possible to create one manually.
> 
> The humanoid mujoco xml file has some error for deepmimic humanoid. Would you release the right vision later?

I guess `dp_env_v3.xml` is what you want.

**Comment by mingfeisun** [comment]
> > Hi, thanks for your interest in the deepmimic mujoco xml.
> > I have no idea of how to do that. I guess there is no way to automate this. It should be possible to create one manually.
> 
> Thanks. I also notice you have commented some thing in deepmimic mujoco xml, but they are defined in deepmimic humanoid, like neck and shoulder. So why are they commented?

The reason that they were commented out was for testing the corectness of the env. They were just used for sanity check. Sorry that they are confusing. I should have removed `humanoid.xm` file. Note that the xml file that is being used is `dp_env_v3.xml'.

**Comment by hellozjj** [comment]
> > > Hi, thanks for your interest in the deepmimic mujoco xml.
> > > I have no idea of how to do that. I guess there is no way to automate this. It should be possible to create one manually.
> > 
> > 
> > Thanks. I also notice you have commented some thing in deepmimic mujoco xml, but they are defined in deepmimic humanoid, like neck and shoulder. So why are they commented?
> 
> The reason that they were commented out was for testing the corectness of the env. They were just used for sanity check. Sorry that they are confusing. I should have removed `humanoid.xm` file. Note that the xml file that is being used is `dp_env_v3.xml'.

@mingfeisun  Thanks very much!

**Comment by mingfeisun** [comment]
> > > > Hi, thanks for your interest in the deepmimic mujoco xml.
> > > > I have no idea of how to do that. I guess there is no way to automate this. It should be possible to create one manually.
> > > 
> > > 
> > > Thanks. I also notice you have commented some thing in deepmimic mujoco xml, but they are defined in deepmimic humanoid, like neck and shoulder. So why are they commented?
> > 
> > 
> > The reason that they were commented out was for testing the corectness of the env. They were just used for sanity check. Sorry that they are confusing. I should have removed `humanoid.xm` file. Note that the xml file that is being used is `dp_env_v3.xml'.
> 
> @mingfeisun Thanks very much!

If you have more questions, please reopen this issue and lets discuss.

**Comment by hellozjj** [comment]
> > > > > Hi, thanks for your interest in the deepmimic mujoco xml.
> > > > > I have no idea of how to do that. I guess there is no way to automate this. It should be possible to create one manually.
> > > > 
> > > > 
> > > > Thanks. I also notice you have commented some thing in deepmimic mujoco xml, but they are defined in deepmimic humanoid, like neck and shoulder. So why are they commented?
> > > 
> > > 
> > > The reason that they were commented out was for testing the corectness of the env. They were just used for sanity check. Sorry that they are confusing. I should have removed `humanoid.xm` file. Note that the xml file that is being used is `dp_env_v3.xml'.
> > 
> > 
> > @mingfeisun Thanks very much!
> 
> If you have more questions, please reopen this issue and lets discuss.

Ok, thanks very much. I think your answer has solved my problem.

**Comment by hellozjj** [comment]
Could you tell me how did you get the deepmimic.xml file？I want to build a .xml file for my own character, but I have no clue how to do this.

**Comment by mingfeisun** [comment]
I was using this as a reference when creating the xml file: http://www.mujoco.org/book/XMLreference.html 
This repo also gives a bunch of good examples of using xml in Mujoco: https://github.com/deepmind/dm_control/tree/master/dm_control/suite
