### ISSUE TITLE
what's the hyper-params used to train imitations of walking/running?

### ISSUE THREAD

**Issue by Maqingyang** [mingfeisun/DeepMimic_mujoco#5]
Thanks for your great work!
I followed #3 to replicate the results but failed. I am wondering what I am doing wrong. Could you post your hyper-params of trpo? I think that will help a lot.

**Comment by mingfeisun** [comment]
You can download one of my trainings here (the policy and training logs are also there for your reference): https://www.dropbox.com/s/0p0gtocqcfhw3lr/src_walk_ok_done_early_horizon_2048.zip?dl=0

Two parameters, the batch_size and number of mpi process, matter a lot. Hope you find it useful

**Comment by Maqingyang** [comment]
Thank you so much! now I can replicate your results! Great Work!
One interesting thing I notice is that, you have implemeted the gail version of Deepmimic in gail_trpo.py. I am curious dose it also work?

**Comment by mingfeisun** [comment]
Basically it's not working. GAIL requires a huge amount of demonstration data (state-action pairs) to approximate the distribution. With only one episode of demonstration, GAIL fails to work.
