### ISSUE TITLE
How do you generate the humanoid3d.txt into .xml files?

### ISSUE THREAD

**Issue by harrison84125** [mingfeisun/DeepMimic_mujoco#7]
As the title tells, I'm curious about this. Since I'm trying to transform the deepmimic character file into urdf format, searching for some methods.

**Comment by mingfeisun** [comment]
Hey, thanks for asking this. As far as I know, there was no automatic way to translate deepmimic txt file into urdf when this project was developed. So the xml model file in this repo was "handcrafted", using humanoid3d.txt as the reference but adding changes to best adapt to Mujoco simulator. You might see there are some difference between these two models if you check the xml in detail. For urdf model, you can google how it can be translated from mujoco xml file (there should be ways to do that and I also saw some projects did that). Best luck!

**Comment by harrison84125** [comment]
Thanks! You give a clear thought on my question. Now I'm working on different character, and I think I should also "handcraft" the file better. Keep going!
