### ISSUE TITLE
How to train the policy for spinkick?

### ISSUE THREAD

**Issue by MetaAnimation** [mingfeisun/DeepMimic_mujoco#8]
Thanks for your great work, could you please offer some details about how to design the reward function for the task of spinkick?

**Comment by mingfeisun** [comment]
The details of reward funciton should be the same as what's been implemented in this codebase. You may need to tune other hyperparameters. You may need to refer to https://github.com/mingfeisun/DeepMimic_mujoco/issues/3 for further details.
