### ISSUE TITLE
version issue and about OpenGL

### ISSUE THREAD

**Issue by hongruijia** [mingfeisun/DeepMimic_mujoco#9]
Hello! When I run the dp_env_v3.py, there is a mistake.
```
mujoco_env.MujocoEnv.__init__(self, xml_file_path, 1)
TypeError: __init__() missing 1 required positional argument: 'observation_space'
```
My Mujoco is 2.1.0 and the mujoco-py is 2.1.2.14.
Is it a version issue?
Any help would be great !

And I would like to know if OpenGL3.3 needs to be installed on a Linux server to run this code.
Although the server is equipped with RTX 3080 and graphics card driver 510.47.03, my server can still only install OpenGL3.1 Mesa 21.2.6. Is this a problem with graphics card drivers? Is there anything else I need to do to upgrade OpenGL version to 3.2 or higher?

**Comment by mingfeisun** [comment]
hey, many thanks for your questions. I guess it's very likely to be a version. The implementation only worked for mujoco200,  and the compatible mujoco should be 1.50.1.68. 

For the OpenGL, I don't the version matters, as long as you can run mujoco simulator there (first test if the OpenGL supports mujoco simulator).

**Comment by hongruijia** [comment]
Thank you for your reply!
